Feature 31 jako user chcialbym miec mozliwosc wyboru grupy podczas tworzenia wydarzenia grupowego
akademia-envelo-3/moovelo-front pull request #112
Opened 2023-01-23 15:45 UTC by maciekw129

[preview](url)
Task: #31 

<details><summary>Baza Danych JSON</summary>

```json
{
  "groups": [
    {
      "id": 1,
      "name": "Liga szydełkowa"
    },
    {
      "id": 1,
      "name": "Gramy w tenisa"
    },
    {
      "id": 1,
      "name": "Piwko ponad wszystko"
    }
  ]
}
```
</details>

2023-01-23 15:46 UTC, maciekw129 commented on src/app/features/create-event/create-event-form.service.ts
> +}
W razie czego tutaj pokazuje się zmiana dlatego, że zmieniłem nazwę sewisu

2023-01-23 15:47 UTC, maciekw129 commented on src/app/features/create-event/create-event.service.ts
> -    });
Tutaj tak samo, została zmieniona tylko nazwa

2023-01-24 07:21 UTC, akademiaEnvelo requested changes

2023-01-24 07:21 UTC, akademiaEnvelo commented on src/app/features/create-event/create-event.interface.ts
> +export interface FetchedGroup {
czemu dodałeś prefix Fetched?

2023-01-24 07:21 UTC, akademiaEnvelo commented on src/app/features/create-event/create-event.module.ts
> +  providers: [CreateEventFormService, { provide: MAT_DATE_LOCALE, useValue: 'en-GB' }],
czy na pewno chcesz ten serwis rejestrować w module? czy nie chcemy być za każdym razem jhak użytkownik będzie chciał stworzyć event to właśnie tworzyć serwis, ktory będzie trzymał nam stan formularza?

2023-01-24 07:21 UTC, akademiaEnvelo commented on src/app/features/create-event/create-event.service.ts
> +    return this.http.get<FetchedGroup[]>(`${this.API_URL}groups`);
nie zjadłeś `/` przed groups? url api to przykładowo `http://localhost:3000` bez `/` na końcu

2023-01-24 07:42 UTC, GBN6 requested changes

2023-01-24 07:42 UTC, GBN6 commented on src/app/features/create-event/event-details-form/event-details-form.component.html
> +        <mat-option *ngFor="let group of groups" [value]="group.id">{{ group.name }}</mat-option>
Nie brakuje tutaj $ w `groups`? Linijka 21 `*ngIf="groups$`

2023-01-24 11:26 UTC, akademiaEnvelo approved these changes

2023-01-24 11:26 UTC, akademiaEnvelo commented on src/app/features/create-event/create-event/create-event.component.ts
> +    this.createEventFormService.getForm().reset();
niech to będzie po prostu metoda reset, a implementacje czy `getForm().reset()` będzie już zamknięta w serwisie. Wtedy też bedzie trzeba prawdopdobnie stworzyć nowy formularz dla pewności, że nie ma żadnej zmiany ze starego

2023-01-24 13:00 UTC, LukaszPietrzykowski16 approved these changes

2023-01-24 13:27 UTC, GBN6 approved these changes

2023-01-25 07:56 UTC, merged