Feature #4 user moze wyswietlic wszystkie wydarzenia do ktorych ma dostep
akademia-envelo-3/moovelo-front pull request #113
Opened 2023-01-24 09:35 UTC by JRRBorkowski

[Preview](https://feature-4-user-moze-wyswietlic-wszystkie-wydarzenia-do-ktorych-ma-dostep--moovelo-envelo.netlify.app/events)

Link do taska:
#4 

Baza danych: 
```
{
  "events": [
      {
          "id": 1,
          "eventInfo": {
              "name": "Giga Koks Turbo Event",
              "category": {
              "id": 1,
              "name": "Piwo"
              },
              "startDate": "20.01.2023",
              "hashtags": [
              {
                "id": 1,
                "value": "piwo"
              },
              {
                "id": 2,
                "value": "GigaTurboEssaKoks"
              }
              ],
              "isConfirmationRequired": false,
              "isPrivate": false,
              "group": false,
              "isCyclic": true,
              "city": "Warszawa",
              "acceptedStatusUsers": 10
              }
      },
      {
          "id": 2,
          "eventInfo": {
              "name": "Giga Koks Turbo Event",
              "category": {
              "id": 2,
              "name": "Piwo"
              },
              "startDate": "20.01.2023",
              "hashtags": [
                  {
              "id": 1,
              "value": "piwo"
              },
              {
              "id": 2,
              "value": "GigaTurboEssaKoks"
              }
              ],
              "isConfirmationRequired": false,
              "isPrivate": true,
              "group": false,
              "isCyclic": true,
              "city": "Warszawa",
              "acceptedStatusUsers": 10
              }
          }
      ]
}
```

2023-01-24 10:33 UTC, maciekw129 requested changes

2023-01-24 10:33 UTC, maciekw129 commented on package.json
> +    "json-server": "^0.17.1",
Wydaje mi się, że nie powinniśmy tego dodawać do dependencies

2023-01-24 10:33 UTC, maciekw129 commented on src/app/features/event/event-list/event-list.component.html
> +      <p>wydarzenie</p>
Czy te elementy p w buttonie są potrzebne?

2023-01-24 10:33 UTC, maciekw129 commented on src/app/features/event/event-list/event-list.component.html
> +    <button class="event-list__button" mat-fab extended color="primary" (click)="createNewEvent()">
Tutaj zamiast dodawać logikę na przejście na innego routa w komponencie, możemy użyć po prostu routerLink: `<button routerLink="jakiś-rout">jakiś button</button>`

2023-01-24 10:33 UTC, maciekw129 commented on src/app/features/event/event-list/event-list.component.ts
> +  providers: [EventListService],
Wydaje mi się, że nie musimy go providować, nie trzyma on żadnego stanu

2023-01-24 10:33 UTC, maciekw129 commented on src/app/features/home/home.module.ts
> +          { path: 'events', loadChildren: () => import('../event/event-list/event-list.module') },
Chyba prettier nie zadziałał

2023-01-24 11:20 UTC, JRRBorkowski commented on src/app/features/event/event-list/event-list.component.html
> +      <p>wydarzenie</p>
Chciałem rozdzielić Stwórz i wydarzenie, żeby nie były w jednej linii, a wolę nie używać br.

2023-01-25 08:09 UTC, JRRBorkowski commented on src/app/features/home/home.module.ts
> +          { path: 'events', loadChildren: () => import('../event/event-list/event-list.module') },
Właśnie problem w tym, że zadziałał i zrobił coś takiego

2023-01-25 08:22 UTC, JRRBorkowski commented on src/app/features/event/event-list/event-list.component.html
> +    <button class="event-list__button" mat-fab extended color="primary" (click)="createNewEvent()">
Poprawione

2023-01-25 11:16 UTC, akademiaEnvelo approved these changes

2023-01-25 13:49 UTC, maciekw129 approved these changes

2023-01-25 15:13 UTC, LukaszPietrzykowski16 approved these changes

2023-01-26 13:24 UTC, annkierl approved these changes

2023-01-26 13:30 UTC, merged