Feature #88 wykonanie interceptora i serwisu
akademia-envelo-3/moovelo-front pull request #114
Opened 2023-01-24 11:17 UTC by annkierl

2023-01-24 12:46 UTC, LukaszPietrzykowski16 approved these changes

2023-01-24 14:07 UTC, maciekw129 requested changes

2023-01-24 14:07 UTC, maciekw129 commented on src/app/shared/loader/cow-loader.component.ts
> +  loaderService = inject(LoaderService);
Nie powinniśmy mieć zainjectowanego serwisu jako publiczny, powinien być private i osobno przypisać do innego publicznego pola isLodaing$

2023-01-25 13:24 UTC, akademiaEnvelo approved these changes

2023-01-25 13:49 UTC, maciekw129 approved these changes

2023-01-25 13:55 UTC, merged