Dodac przekierowanie do strony glownej 119
akademia-envelo-3/moovelo-front pull request #128
Opened 2023-01-25 15:42 UTC by LukaszPietrzykowski16

link:

2023-01-26 06:21 UTC, akademiaEnvelo requested changes

2023-01-26 06:21 UTC, akademiaEnvelo commented on src/app/features/home/user-navbar/navbar.component.html
> +    <header class="nav-bar__logo" routerLink="/">
klikalny powinien byc albo element button albo a, dlatego w headerze opakujmy content w `a` i na nim dodajmy router link'a

2023-01-26 09:18 UTC, GBN6 approved these changes

2023-01-26 14:26 UTC, akademiaEnvelo approved these changes

2023-01-27 09:57 UTC, maciekw129 approved these changes

2023-01-27 09:59 UTC, merged