feature-98-wyswietl-zadeklarowych-uczestnikow
akademia-envelo-3/moovelo-front pull request #132
Opened 2023-01-26 08:56 UTC by GBN6

### Task 
- #98 

### Preview
[LINK](https://feature-98-wyswietl-zadeklarowych-uczestnikow--moovelo-envelo.netlify.app/theme)

2023-01-27 14:05 UTC, akademiaEnvelo requested changes

2023-01-27 14:05 UTC, akademiaEnvelo commented on src/app/features/event/event-participants/event-participants-list/event-participants-list.component.html
> +    </ng-container>
ten komponent moze przyjac okreslony label do nazwania grupy uczestników, dzieki temu bedziemy mogli nie powtarzac tej logiki i wyrzucic visitorów na zewnątrz. Dzięki czemu komponetn bedzie bardziej generyczny

2023-01-27 14:05 UTC, akademiaEnvelo commented on src/app/features/event/event-participants/event-participants.component.html
> +      <div class="event-participants__button">
ten ng container zbedny, mozemy wrzucic petle na div

2023-01-27 14:29 UTC, GBN6 commented on src/app/features/event/event-participants/event-participants-list/event-participants-list.component.html
> +    </ng-container>
Poprawione.

2023-01-27 14:29 UTC, GBN6 commented on src/app/features/event/event-participants/event-participants.component.html
> +      <div class="event-participants__button">
Zrobione.

2023-01-27 14:55 UTC, LukaszPietrzykowski16 commented on src/app/features/event/event-participants/event-participants.component.html
> +        <p *ngIf="status !== 'accepted'; else acceptedAndVisitors" class="font-heading-3">
buttony z globalnych stanów lub zmiena BEM

2023-01-27 14:55 UTC, LukaszPietrzykowski16 commented on src/app/features/event/event-participants/event-participants-list/event-participants-list.component.html
> +    <li class="event-participants__list__item font-text-1" *ngFor="let participant of participantsList">
2 zagnieżdżenia w BEM

2023-01-27 14:55 UTC, LukaszPietrzykowski16 commented on src/app/features/event/event-participants/event-participants.component.scss
> +    cursor: pointer;
zajebisty pointer, fajnie że pamiętałeś UwU

2023-01-27 15:11 UTC, GBN6 commented on src/app/features/event/event-participants/event-participants.component.html
> +        <p *ngIf="status !== 'accepted'; else acceptedAndVisitors" class="font-heading-3">
Poprawione.

2023-01-27 15:11 UTC, GBN6 commented on src/app/features/event/event-participants/event-participants-list/event-participants-list.component.html
> +    <li class="event-participants__list__item font-text-1" *ngFor="let participant of participantsList">
Poprawione.

2023-01-27 15:17 UTC, LukaszPietrzykowski16 approved these changes
👍

2023-01-30 10:29 UTC, akademiaEnvelo approved these changes

2023-01-31 07:43 UTC, merged