feat: interceptors implemented
akademia-envelo-3/moovelo-front pull request #141
Opened 2023-01-30 11:49 UTC by annkierl

2023-01-30 13:03 UTC, annkierl commented on src/app/features/create-event/event-details-form/event-details-form.component.html
> +<div *ngIf="errorClientServer$ | async; else success">
Szybkie wprowadzenie jak na to patrzeć:
Tutaj obsługa globalna błędu z serwisu/klienta

2023-01-30 13:03 UTC, annkierl commented on src/app/features/create-event/event-details-form/event-details-form.component.html
> +    <app-cow-loader></app-cow-loader>
Tutaj dodanie  globalnego loadera

2023-01-30 13:03 UTC, annkierl commented on src/app/features/create-event/event-details-form/event-details-form.component.html
> +</ng-template>
</ng-template>
tutaj zamknięcie obsługi błędów z serwer/klient

2023-01-30 13:03 UTC, annkierl commented on src/app/features/create-event/event-details-form/event-details-form.component.html
> +<ng-template #success>
Tutaj obsługa globalna błędu z serwisu/klienta gdy jest sukces

2023-01-30 13:51 UTC, GBN6 requested changes

2023-01-30 13:51 UTC, GBN6 commented on src/app/features/create-event/event-details-form/event-details-form.component.ts
> +  private errorService = inject(ErrorhandlerService);
W celu czytelności dodawajmy wszystkie injecty jeden po sobie:
```
inject
inject
inject

subject
```

2023-01-30 14:03 UTC, annkierl commented on src/app/features/create-event/event-details-form/event-details-form.component.ts
> +  private errorService = inject(ErrorhandlerService);
Done.

2023-01-30 14:19 UTC, GBN6 approved these changes

2023-01-30 15:19 UTC, JRRBorkowski approved these changes

2023-01-31 12:41 UTC, akademiaEnvelo approved these changes

2023-01-31 13:15 UTC, merged