Feature #81 user widzi czlonkow grupy
akademia-envelo-3/moovelo-front pull request #166
Opened 2023-02-02 15:53 UTC by annkierl

2023-02-03 08:02 UTC, maciekw129 requested changes

2023-02-03 08:02 UTC, maciekw129 commented on src/app/features/group/single-group/single-group.component.html
> +          <button [routerLink]="['users']" class="group-info__button" mat-flat-button color="primary">
router link nie musi być dynamiczną wartością, możemy po prostu zrobić: `routerLink="/users"`

2023-02-03 08:02 UTC, maciekw129 commented on src/app/features/group/single-group/single-group.component.html
> +          <button [routerLink]="['users']" class="group-info__button" mat-flat-button color="primary">
I nie jestem pewny, ale chyba jak jest element button to przekierowanie powinno być w funkcji

2023-02-03 11:09 UTC, GBN6 requested changes

2023-02-03 11:09 UTC, GBN6 commented on src/app/features/group/single-group/group-participants/group-participants.html
> +  </ng-container>
W `async as users$` ten `$` już chyba nie jest potrzebny

2023-02-07 08:50 UTC, annkierl commented on src/app/features/group/single-group/single-group.component.html
> +          <button [routerLink]="['users']" class="group-info__button" mat-flat-button color="primary">
done

2023-02-07 08:50 UTC, annkierl commented on src/app/features/group/single-group/group-participants/group-participants.html
> +  </ng-container>
done

2023-02-07 08:57 UTC, GBN6 requested changes

2023-02-07 08:57 UTC, GBN6 commented on src/app/features/group/single-group/group-participants/group-participants.html
> +<app-cow-loader></app-cow-loader>
Zgodnie ze znalezionym problemem z wyświetlaniem błedu,  
```
<div *ngIf="errorClientServer$ | async; else success">
  <app-error></app-error>
</div>
```
błąd przenieśmy na sam dół, a niech pierwszym będzie `<ng-container *ngIf="users$ | async as users">`
Wygłądało by to następująco 
```
<ng-container *ngIf="users$ | async as users; else error">
....
</ng-container>
<ng-template #error>
<div *ngIf="errorClientServer$ | async">
  <app-error></app-error>
</div>
</ng-template>

2023-02-13 07:09 UTC, GBN6 approved these changes

2023-02-14 09:13 UTC, akademiaEnvelo approved these changes

2023-02-14 15:23 UTC, maciekw129 approved these changes

2023-02-14 15:25 UTC, merged