Feature 33 jako user chcialbym miec mozliwosc dodawania hashtagow w formularzu tworzenia wydarzenia
akademia-envelo-3/moovelo-front pull request #168
Opened 2023-02-03 13:30 UTC by maciekw129

task: #33

2023-02-03 14:20 UTC, GBN6 approved these changes

2023-02-06 10:58 UTC, LukaszPietrzykowski16 approved these changes

2023-02-07 07:29 UTC, akademiaEnvelo requested changes

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/create-event.service.ts
> +  // getting all hashtags as array of strings
ten komentarz jest zbedny, nazwa sugeruje nam co pobiera, a typ mówi nam o formie

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/event-details-form/event-details-form.component.html
> +              >Hashtag może mieć maksymalnie 20 znaków.</ng-container
czy tych wartości `2` i `20` w komuniaktach o błędzie nie mamy zaszyte w obiekcie z błędem? jeśli tak to użyjmy ich zamiast hardkodować wartość

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/event-details-form/event-details-form.component.scss
> +  padding-right: 0 !important;
nie możemy wzmocnić selektora bez flagi `!important` ?

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/event-details-form/event-details-form.component.ts
> +    }
czemu splice a nie np. filter?

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/event-details-form/event-details-form.component.ts
> +      return;
owrapujmy ten return w wąsy `{}` bo jesto bardzo nieczytelne

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/event-details-form/event-details-form.component.ts
> +    event.chipInput!.clear();
zamiast wymuszać na kompilatorze `!` sprawdźmy czy `chipInput` istneije w warunku wejściowym w tej funkcji

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/event-details-form/event-details-form.component.ts
> +    this.eventDetailsForm = this.createEventForm.getForm().controls.eventDetailsForm;
możemy to zrobić bezpośrednio w przypisaniu pola, nie potrzebujemy tego robić w constructorze

2023-02-07 07:29 UTC, akademiaEnvelo requested changes

2023-02-07 07:29 UTC, akademiaEnvelo commented on src/app/features/create-event/validators/hastagLengthValidators.ts
> +  console.log(value);
console.log

2023-02-07 09:11 UTC, maciekw129 commented on src/app/features/create-event/event-details-form/event-details-form.component.scss
> +  padding-right: 0 !important;
Próbowałem na wiele różnych sposobów i bez `!important` mi nie wchodziło

2023-02-07 09:11 UTC, maciekw129 commented on src/app/features/create-event/event-details-form/event-details-form.component.ts
> +    }
Tak szczerze to dlatego, że tak było na stronie materiala xD

2023-02-07 09:18 UTC, akademiaEnvelo approved these changes

2023-02-10 09:48 UTC, merged