Event card new design
akademia-envelo-3/moovelo-front pull request #172
Opened 2023-02-08 10:45 UTC by LukaszPietrzykowski16

2023-02-08 12:38 UTC, GBN6 requested changes

2023-02-08 12:38 UTC, GBN6 commented on src/app/features/event/event-card-new/event-card-new.component.scss
> +    background-image: url('../../../../assets/eventpicture.png');
Czy krótsza ścieżka `url('/assets/eventpicture.png')` zadziała ?

2023-02-08 15:21 UTC, LukaszPietrzykowski16 commented on src/app/features/event/event-card-new/event-card-new.component.scss
> +    background-image: url('../../../../assets/eventpicture.png');
zmienione 👺

2023-02-09 09:26 UTC, GBN6 approved these changes

2023-02-27 14:18 UTC, akademiaEnvelo approved these changes

2023-03-07 10:47 UTC, akademiaEnvelo requested changes

2023-03-07 10:47 UTC, akademiaEnvelo commented on src/app/features/event/event-card/event-card.component.ts
> +  @ViewChild('hashtagsContainer') hashtagsContainer!: ElementRef<HTMLUListElement>;
wydaje mi sie ze mozesz ustawic ten element jako statyczny skoro jest nie jest ladowany dynanamicznie (drugi parametr decoratora viewChild, opcja static) i wtedy bedziesz mial juz dostep do tego elementu w `ngOnInit`, dzieki temu tam wykonasz cala logikę i prawodpodobnie nie bedziesz musial recznie wywowlywac rerenderu

2023-03-08 09:02 UTC, akademiaEnvelo approved these changes

2023-03-08 09:26 UTC, merged