Feature #159 formularz tworzenia grupy
akademia-envelo-3/moovelo-front pull request #173
Opened 2023-02-08 11:27 UTC by GBN6

### Task
- #159 

### Preview
[LINK](https://feature-159-formularz-tworzenia-grupy--moovelo-envelo.netlify.app/create-group)

### Baza danych w pliku db.json
[LINK](https://github.com/maciekw129/automatic-guacamole)

2023-02-08 12:09 UTC, LukaszPietrzykowski16 requested changes

2023-02-08 12:09 UTC, LukaszPietrzykowski16 commented on src/app/features/create-group/create-group/create-group.component.ts
> +
W nazwie tworzenia wydarzenia, jak w opisie możemy dać pustego stringa. 
Nazwa wydarzenia: '            ' 
Opis: '                       '

2023-02-08 12:09 UTC, LukaszPietrzykowski16 commented on src/app/features/create-group/create-group.interface.ts
> +  name: string;
id powinno być zawsze, więc czy aby na pewno ten znak zapytania jest konieczny?

2023-02-08 12:46 UTC, GBN6 commented on src/app/features/create-group/create-group.interface.ts
> +  name: string;
Przy tworzeniu grupy nie musimy wysłać `id`, body requestu składa się tylko z `name` i `description`. `ID` jest tutaj `optional` polem ponieważ potrzebny był przy responsie na `POST` aby zmockować przekierowanie do odpowiedniej grupy.

2023-02-08 13:23 UTC, LukaszPietrzykowski16 commented on src/app/features/create-group/create-group.interface.ts
> +  name: string;
ale id w db.jsonie się zawsze tworzy (jak dodawałem, z jakiegoś powodu tworzył się id 2138), a backend raczej też będzie tworzyć w każdym obiekcie który był w bazie danych, więc nie wiem czy taki opcjonaly... albo się po prostu czepiam dla samego czepiania się...

2023-02-08 13:33 UTC, GBN6 commented on src/app/features/create-group/create-group.interface.ts
> +  name: string;
Tak, tworzy się zawsze, ale jeśli otypuję body `POST` bez opcjonalnego pola `id` (tak jak jest w oryginalnym endpoincie) to następnie nie mogę się do niego odnieść w funkcji aby przekierować użytkownika do groupy o odpowiednim `id`. Mówiąc inaczej, wysłać `POST`-em id nie muszę, ale potrzebuję go podczas zwrotu po `POST` aby przenieść użytkownika do strony grupy dlatego użyłem opcjonalnego pola

2023-02-09 12:29 UTC, maciekw129 requested changes

2023-02-09 12:29 UTC, maciekw129 commented on src/app/features/group/single-group/single-group.component.html
> +          <ng-container *ngIf="singleGroup.groupMembers.length === 0; else groupMembers">
Nie trzeba przyrównywać do zera, zero i tak jest falsy

2023-02-09 12:29 UTC, maciekw129 commented on src/app/features/group/single-group/single-group.component.html
> +            <img src="/assets/logo-mascot.png" class="error__logo__image" alt="no events site logo" />
W bem takie podwójne zagnieżdżenia są chyba błędne

2023-02-09 12:29 UTC, maciekw129 commented on src/app/features/group/single-group/single-group.component.html
> +          <ng-container *ngIf="singleGroup.events.length === 0; else groupEvent">
Tak jak wyżej

2023-02-09 15:04 UTC, GBN6 commented on src/app/features/create-group/create-group/create-group.component.ts
> +
Dodany validator

2023-02-09 15:09 UTC, maciekw129 approved these changes

2023-02-09 15:21 UTC, LukaszPietrzykowski16 approved these changes

2023-02-10 10:53 UTC, akademiaEnvelo requested changes

2023-02-10 10:53 UTC, akademiaEnvelo commented on src/app/features/create-group/create-group.interface.ts
> +  name: string;
stwórzmy w takim razie dwa interfejsy, jeden z a drugi bez id

2023-02-13 07:26 UTC, GBN6 commented on src/app/features/group/single-group/single-group.component.html
> +          <ng-container *ngIf="singleGroup.groupMembers.length === 0; else groupMembers">
Poprawione

2023-02-13 07:26 UTC, GBN6 commented on src/app/features/group/single-group/single-group.component.html
> +            <img src="/assets/logo-mascot.png" class="error__logo__image" alt="no events site logo" />
Poprawione

2023-02-13 07:35 UTC, GBN6 commented on src/app/features/create-group/create-group.interface.ts
> +  name: string;
Dodałem interfejs

2023-02-13 11:32 UTC, akademiaEnvelo approved these changes

2023-02-14 10:48 UTC, merged