Feature 8 user moze filtrowac sortowac i sortowac po kategoriach w liscie wydarzen
akademia-envelo-3/moovelo-front pull request #174
Opened 2023-02-08 11:28 UTC by maciekw129

task: #8

2023-02-08 12:32 UTC, GBN6 requested changes

2023-02-08 12:32 UTC, GBN6 commented on src/app/features/event/event-list/event-list.component.html
> +        </menu>
Czy tutaj nie powinien być jakis `ngIf="categories$ | async as categories"` i dopiero potem `*ngFor` skoro jest to zapytanie do bazy i coś może pójść nie tak?

2023-02-08 12:32 UTC, GBN6 commented on src/app/features/event/event-list/event-list.component.ts
> +  events$$ = this.eventListService.events$;
W `events$$` chyba  jeden znak `$` za duzo, ponieważ to observable.

2023-02-09 11:22 UTC, GBN6 approved these changes

2023-02-09 15:46 UTC, akademiaEnvelo approved these changes

2023-02-09 15:46 UTC, akademiaEnvelo commented on src/app/features/event/event-list/event-list.component.html
> +            <button (click)="resetCategory(); $event.stopPropagation()">Resetuj kategorię</button>
dorzuć taska na dyrektywke z wykorzystaniem stopeventpropagation na clicka

2023-02-09 15:46 UTC, akademiaEnvelo commented on src/app/features/event/event-list/event-list.component.ts
> +  private unsubscribe$$ = new Subject<void>();
też taska poproszę na wyrzucenie tego do hooka i uzywanie `takeUntil`

2023-02-13 11:46 UTC, akademiaEnvelo requested changes

2023-02-13 11:46 UTC, akademiaEnvelo commented on src/app/features/event/event-list/event-list.component.ts
> -import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
trochę za dużo się dzieje w tym komponencie, proponuje filtrowanie i sortowanei wyniesc do innego komponentu i tutaj go tylko użyć

2023-02-13 11:46 UTC, akademiaEnvelo commented on src/app/features/event/event-list/event-list.interface.ts
> +export type FilterValue = 'participating=true' | 'group=true';
typescript tip

```typescript
type SortOrder = 'asc' | 'desc';
type SortProperty = 'sortOrder' | 'participants';
type SortValue = `${SortProperty}=${SortOrder }`;
```

2023-02-14 13:14 UTC, akademiaEnvelo approved these changes

2023-02-15 07:35 UTC, merged