Feature 150 utworzenie zebatki
akademia-envelo-3/moovelo-front pull request #179
Opened 2023-02-13 11:40 UTC by maciekw129

task: #150

2023-02-14 14:35 UTC, GBN6 requested changes

2023-02-14 14:35 UTC, GBN6 commented on src/app/shared/settings/menuVariants.ts
> +  },
Wydaje mi się, że tutaj brakuje opcji do zaproszenia kogoś na event wewnętrzny prywatny w `event.eventOwner`.

2023-02-23 07:58 UTC, GBN6 approved these changes

2023-02-27 14:24 UTC, akademiaEnvelo approved these changes

2023-02-27 14:32 UTC, merged