feat: loader cow component
akademia-envelo-3/moovelo-front pull request #60
Opened 2023-01-10 09:59 UTC by LukaszPietrzykowski16

2023-01-10 10:34 UTC, annkierl requested changes

2023-01-10 10:34 UTC, annkierl commented on src/app/shared/loader/style.css
> +    /* this value could be change*/
do usunięcia linijka z komentarzem.

2023-01-10 10:34 UTC, annkierl commented on src/app/shared/loader/cow-loader.component.ts
> +      <p> Ładowanie... </p>
Przy animacji obrazek zahacza o napis "ładowanie... ". Fajnie by było zwiększyć odległość, ale to bardziej sugestia.

2023-01-10 10:39 UTC, LukaszPietrzykowski16 commented on src/app/shared/loader/cow-loader.component.ts
> +      <p> Ładowanie... </p>
zmienie odstęp na większy

2023-01-10 11:14 UTC, akademiaEnvelo requested changes

2023-01-10 11:14 UTC, akademiaEnvelo commented on src/app/app.module.ts
> +
zbędna linijka

2023-01-10 11:14 UTC, akademiaEnvelo commented on src/app/shared/loader/cow-loader.component.ts
> +
zbędna linijka

2023-01-10 11:14 UTC, akademiaEnvelo commented on src/app/shared/loader/style.css
> +
zbędna linijka

2023-01-10 11:14 UTC, akademiaEnvelo commented on src/app/shared/loader/cow-loader.component.ts
> +      <img src="/assets/logo.png">
wymagany atrybut `alt`

2023-01-10 11:14 UTC, akademiaEnvelo commented on src/app/shared/loader/style.css
> +    padding-top: 2rem;
proponuję paddingi, marginesy oraz bordery ogarniać sobie pixelami

2023-01-12 09:30 UTC, GBN6 approved these changes

2023-01-12 13:23 UTC, annkierl approved these changes
dobrze to wygląda, jak dla mnie można mergować :)

2023-01-12 13:23 UTC, annkierl commented on src/app/shared/loader/style.css
> +}
lepiej wygląda teraz 👍

2023-01-13 07:17 UTC, akademiaEnvelo approved these changes

2023-01-13 07:17 UTC, akademiaEnvelo commented on src/app/shared/loader/style.css
>  }
co tu się zadziało xD

2023-01-13 07:17 UTC, akademiaEnvelo commented on src/app/core/theme.component.ts
> +    <app-cow-loader> </app-cow-loader>
dodajemy tutaj jeszcze naglówke jakis z nazwą kompoentnu ktory wyswietlamy

2023-01-13 08:23 UTC, LukaszPietrzykowski16 commented on src/app/shared/loader/style.css
>  }
testowałem czy esLint działa (nie działał xD)

2023-01-13 08:38 UTC, merged